version: '3.8'

services:
  web:
    build: .
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/P13_OCLettings/website.sqlite3  # Assurez-vous que cette ligne est correctement configurée pour votre fichier SQLite
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Remplacer par '0' en production
