version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - DJANGO_SECRET_KEY
    env_file:
      - .env
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/P13_OCLettings/website.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0