version: 2.1

orbs:
  python: circleci/python@1.2.0
  docker: circleci/docker@0.5.20

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests and Check Coverage
          command: |
            pip install pytest pytest-cov
            pytest --cov=. --cov-report=term --cov-fail-under=80
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  build-docker-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build --build-arg DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} -t oclettingswebsite_v2:$CIRCLE_SHA1 .
      - run:
          name: Docker Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Docker Push
          command:
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag myapp:$CIRCLE_SHA1 $DOCKER_USERNAME/oclettingswebsite_v2:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/oclettingswebsite_v2:$CIRCLE_SHA1


  deploy-to-render:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |
            # Assurez-vous d'avoir configuré le CLI Render et d'être connecté
            # Cette étape pourrait nécessiter une configuration personnalisée basée sur votre processus de déploiement avec Render.
            # Exemple générique pour déclencher un déploiement via Git
            git push render main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
      #- deploy-to-render:
       #   requires:
         #   - build-docker-image
