version: 2.1

orbs:
  python: circleci/python@1.2.0
  docker: circleci/docker@0.5.20
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests and Check Coverage
          command: |
            pip install pytest pytest-cov
            pytest --cov=. --cov-report=term --cov-fail-under=80
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  build-and-push-docker-image:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/ecr_login:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_DEFAULT_REGION}
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1 .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1

  deploy-to-ecs:
    executor: aws-ecs/default
    steps:
      - aws-ecs/deploy-service-update:
          cluster: ${CLUSTER_NAME}
          service: ${SERVICE_NAME}
          container-image-name-updates: "container=${CONTAINER_NAME},tag=$CIRCLE_SHA1"
          region: ${AWS_REGION}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - build-and-push-docker-image:
          requires:
            - build-and-test
      - deploy-to-ecs:
          requires:
            - build-and-push-docker-image
