version: 2.1

orbs:
  python: circleci/python@1.2.0
  docker: circleci/docker@0.5.20
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-ecs: circleci/aws-ecs@4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests and Check Coverage
          command: |
            pip install pytest pytest-cov
            pytest --cov=. --cov-report=term --cov-fail-under=80
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: arn:aws:iam::767397722620:role/adminrole  #arn:aws:iam::767397722620:user/edwinlrt
                role_session_name: aws_ecr_build_and_push_image
          profile_name: OIDC-USER
          region: ${AWS_DEFAULT_REGION}
          repo: oclettings-website
          tag: ${CIRCLE_SHA1}
          requires:
            - build-and-test
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: arn:aws:iam::767397722620:role/adminrole #arn:aws:iam::767397722620:user/edwinlrt
          cluster: oclettings-website-cluster
          container_image_name_updates: "container=oclettings-website-service,tag=${CIRCLE_SHA1}"
          family: oclettings-website-service
          profile_name: OIDC-USER
          region: ${AWS_DEFAULT_REGION}
          requires:
            - aws-ecr/build_and_push_image
