version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DEBUG: $DEBUG
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t monappdjango .
      - run: docker run -d -p 8000:8000 --name app monappdjango
      - run: sleep 10
      - run: curl --retry 10 --retry-delay 5 -v http://localhost:8000

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
